Se agrega nombre y perfil de github
FooCamp/gitflow-team-2 pull request #5
Opened 2020-06-01 21:06 UTC by MarianaLoaiza

Se agrega nombre y perfil de github

2020-06-01 21:17 UTC, mfbarrera submitted a review, later dismissed
Add more reviewers

2020-06-01 21:57 UTC, caritonaranjo requested changes
mariana, te falta el link de github, el enlace a tu perfil de github

2020-06-01 22:03 UTC, omeneses submitted a review, later dismissed
Falta agregar el link a tu cuenta de

2020-06-01 22:03 UTC, omeneses commented on README.md
> +| Mariana |[MarianaLoaiza](github.link) |
Falta agregar el link a tu github account

2020-06-01 22:05 UTC, MarianaLoaiza commented on README.md
> +| Mariana |[MarianaLoaiza](github.link) |
Listo, ya lo corregí.

2020-06-01 22:30 UTC, caritonaranjo submitted a review, later dismissed

2020-06-01 22:38 UTC, mfbarrera submitted a review, later dismissed

2020-06-02 00:13 UTC, mfbarrera approved these changes

2020-06-02 00:13 UTC, sjaramilloo approved these changes

2020-06-02 00:13 UTC, caritonaranjo approved these changes

2020-06-02 00:17 UTC, merged